### ISSUE TITLE
simple-process: NoSuchMethodError when completing a task in cloud-tasklist

### ISSUE THREAD

**Issue by margue** [holisticon/camunda-bpm-cloud#30]
branch: workload-service-axon

```
2017-03-31 15:20:15.746  ERROR 1 --- [o-auto-1-exec-7] c.b.s.b.s.r.CamundaJerseyResourceConfig] : Allocate exception for servlet org.camunda.bpm.spring.boot.starter.rest.CamundaJerseyResourceConfig

java.lang.NoSuchMethodError: javax.ws.rs.core.Application.getProperties()Ljava/util/Map;
at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:331) ~[jersey-server-2.23.2.jar!/:na]
at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:392) ~[jersey-container-servlet-core-2.23.2.jar!/:na]
at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:177) ~[jersey-container-servlet-core-2.23.2.jar!/:na]
...
```

**Comment by margue** [comment]
see for details: http://stackoverflow.com/questions/39214853/spring-jersey-java-lang-nosuchmethoderror-javax-ws-rs-core-application-getpro
